// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName
// app/javascript/controllers/index.js

import { Application } from "stimulus";
import NotificationController from "./notification_controller";

const application = Application.start();
application.register("notification", NotificationController);

